### ISSUE TITLE
Unexpected spaces in mail content

### ISSUE THREAD

**Issue by zrll12** [karastojko/mailio#100]
I'm sanding a mail including an link using this library, but there are spaces in the mail.
![image](https://user-images.githubusercontent.com/46812903/179438288-26ed4a0c-c33a-4a23-8519-fb80ae71b2f2.png)

**Comment by zrll12** [comment]
> I'm sanding a mail including an link using this library, but there are spaces in the mail. ![image](https://user-images.githubusercontent.com/46812903/179438288-26ed4a0c-c33a-4a23-8519-fb80ae71b2f2.png)

Like this one, there is a space between 2558 and 7, this prevents users from paste the link directly from this email.

**Comment by zrll12** [comment]
Besides, this library garbled at a fixed position.
![image](https://user-images.githubusercontent.com/46812903/179438924-86bbe96f-42d0-432d-927b-f1c6bd0173fd.png)
![image](https://user-images.githubusercontent.com/46812903/179438941-033cf65e-2d11-4929-a0d1-70f71a1b06ac.png)
Like this one, no matter how I change the text, there is unexpected character at a fixed position.

**Comment by karastojko** [comment]
Do you have a minimal example so I could try it on my own?

**Comment by zrll12** [comment]
sure
try {
                mailio::message msg;
                msg.from(mailio::mail_address("Vastsea Admin", config["mail"]["username"].asString()));
                msg.add_recipient(mailio::mail_address("user", mailbox));
                msg.subject("验证您的邮箱");
                msg.content_type(mailio::mime::media_type_t::TEXT, "HTML");
                msg.content((std::string)"https://" + config["baseUrl"].asString() + "verify.html?token=" + str + "<br>欢迎加入瀚海，现在我们需要验证您的邮箱，请访问以上链接继续。本邮件由系统自动发送，如需帮助，请联系群管理，不要回复本邮件!");

                mailio::smtp conn(config["mail"]["smtpHost"].asString(), config["mail"]["smtpPort"].asInt());
                conn.authenticate(config["mail"]["username"].asString(), config["mail"]["token"].asString(),
                                  mailio::smtp::auth_method_t::LOGIN);
                conn.submit(msg);
            } catch (exception e) {
                logger->error(e.what());
            }

**Comment by karastojko** [comment]
If you set the content type to HTML then you should format the content in the same way. However, this is not the root cause of the problem. Suppose you are sending the UTF-8 text
```
msg.content((std::string)"<html><head></head><body><p>https://example.com/verify.html?token=1234567890" + "欢迎加入瀚海</p></body></html>");
```
which is a smaller example but still with the reproducible issue. All letters except Chinese are single byte encoded in UTF-8. The C++ standard library offers only basic stuff for UTF-8, like u8 string literals, `char8_t` and `u8string` starting from C++ 20, and so on. (I am even experiencing different behavior of the UTF-8 string literals with Gcc and VS compilers.) Mail content is formatted into lines, the content is split at some position in a string. For the single byte encoded characters that's fine, but for the multibyte encoded characters like Chinese or Cyrillic it is an issue. Since there is no standard way to cut a string at a given character position but only at a byte position, *mailio* cannot determine whether it splits the mail content into new line in the middle of a multibyte character. That's what it happens in your example: `<html><head></head><body><p>https://example.com/verify.html?token=1234567890\xE6\xAC\r\n\xA2迎加入瀚海</p></body></html>` The bytes `xE6\xAC\xA2` are exactly the character '欢' but unfortunately in a different lines and thus seen as garbled characters.
Unfortunately, there is no solution on *mailio* side until C++ provides more utilities for handling UTF-8, meaning it's up to the library's user to solve the issue. For instance, in this case the new line could be forced with something like
```
msg.content((std::string)"<html><head></head><body><p>https://example.com/verify.html?token=1234567890<br>" + "欢迎加入瀚海</p></body></html>");
```
Check the line break HTML tag to enforce Chinese letters to be in the next line. I know it's not convenient to format the content manually, but that's one approach. Also, there are libraries to manipulate Unicode content, so maybe some of them may ease the content formatting.

**Comment by zrll12** [comment]
I think you can check the byte before cutting it. Like if it starts with 10, then that means it is not the starting byte of a charactor.

**Comment by zrll12** [comment]
I tried to fix using the code below but it seems that some thing has went wrong.

//TODO: check utf8
int a = *ch;
int b;
if (a < 0){//some utf character bytes will be recognized as negative number
    int n=abs(a);
    a = n ^ 0xff;
    a += 1;
}
b = a;
a = a >> 3;//the first 5 bits
int bits = 0;//numbers of 1 in the beginning of a
int bita = 0;//length of a
while(a > 0){
    if (a % 2 == 0){
        bits = 0;
    } else {
        bits += 1;
    }
    a = a >> 1;
    bita ++;
    }
    //std::cout << *ch << " " << b << " " << bits << " " << bita << "\n";
    if (bita == 5 && bits > 1) {//this is the beginning byte of a multibyte character
    if (line_len + bita >= string::size_type(_line_policy)) {//there is no enough space for this character
        enc_text.push_back(line);
        line.clear();
        line_len = 0;
    }
}
line += *ch;
line_len++;
}

**Comment by karastojko** [comment]
That is one case of a UTF-8 character encoded with three bytes. But there are also cases of two and four bytes characters. Also, there is UTF-16 which has to be considered. Furthermore, there are many other encodings not related to Unicode. That's the reason why I would prefer a library like ICU instead of implementing it. The purpose of *mailio* is to deal with protocols instead with encodings.

**Comment by zrll12** [comment]
Thanks. By the way, is there any examples to show how to work with icu4c?

**Comment by karastojko** [comment]
Did you try the ones from this [https://begriffs.com/posts/2019-05-23-unicode-icu.html](blog)?

**Comment by zrll12** [comment]
But how does it work with mailio?

**Comment by karastojko** [comment]
There is no example for icu4c and mailio. The approach would be:
- Fill the `uint8_t bytes[]` in the similar manner as shown in the example `utf8.c` of the aforementioned blog.
- Store them into `body`variable of the type `string` or `u8string`.
- Use the `message::content(body)` to populate the mail message.
