### ISSUE TITLE
Switching to SSL failed

### ISSUE THREAD

**Issue by frank10gm** [karastojko/mailio#148]
I receive this problem when authenticating to smtps: mailio::dialog_error: Switching to SSL failed

It was working before upgrading to: mailio:arm64-osx -> 0.23.0

**Comment by karastojko** [comment]
The version you are using is [this](https://github.com/karastojko/mailio/releases/tag/0.23.0) one?

**Comment by frank10gm** [comment]
Yes, that one. I updated today. 
I tried with gmail smtp.

**Comment by karastojko** [comment]
In the version 0 23 I have imposed the stronger SSL verification by default, which seems to be too much for many email servers. It is fixed in the latest versions. If you still want to stay on 0.23 then you have to change the SSL options by using `smtps::ssl_options()` with the value `dialog::ssl_options_t::

**Comment by frank10gm** [comment]
Thanks! Very good.
Thanks also for this very good library :)

**Comment by frank10gm** [comment]
when do you plan to release 0.24 ?

**Comment by karastojko** [comment]
I cannot say now the date, not even the approximate one. There are few bugs to solve and I would need to add at least one feature in order to declare the new version.
