### ISSUE TITLE
Line policy deprecated

### ISSUE THREAD

**Issue by Spixmaster** [karastojko/mailio#184]
```cpp
message.line_policy(mailio::codec::line_len_policy_t::VERYLARGE, mailio::codec::line_len_policy_t::MANDATORY);
```

`message.line_policy()` and `mailio::codec::line_len_policy_t::VERYLARGE` are deprecated. What to used instead?

Another thing I wonder is that I do not need to call the function anymore. The tests pass. I used to need the function call as some exception was thrown because of too long lines but that is not the case anymore with the new version. What is the reason for that?

**Comment by karastojko** [comment]
There is another method `void mime::line_policy(codec::line_len_policy_t line_policy)` (single parameter) which is meant to unify both the line policy and the old decoding line policy. Internally, the deprecated method now works same as the old one. The reason to keep the old one for a while is not to keep API backward compatible for a while. Instead of the `VERYLARGE` please use `NONE` which does not check the policy at all.
