### ISSUE TITLE
Setting Sender: header

### ISSUE THREAD

**Issue by EarthlingKira** [karastojko/mailio#2]
Dear @karastojko,

let me begin with saying that your email library is exactly what I was looking for, it's a joy to use, thank you for your work.

For our application we will need to set a Sender header (different than From: header), see https://stackoverflow.com/a/14253556 for RFC explanation.

Since we'll need this feature soon I will probably implement this myself in the next days and I would like to create a pull request, would you be willing to accept this pull request? Do you have any requirements for contributors or for this specific feature?

rgds, Kira

**Comment by karastojko** [comment]
Hi Kira,
Thanks for giving a try to _mailio_.

I see the issue, and obviously there is a need for the `Sender:` header. At the same time, the current `From:` header should be fixed to support mailbox list (instead of the current mailbox). Furthermore, one should check how `MAIL FROM:` in SMTP should work.

Anyway, if you are going to fix this in next few days, go ahead. You will be the first contributor, so I will make the Contributors section in the README file and list you, if that is okay with you. I have also semiautomated tests not listed here on Github, so probably I'll need awhile to check if something is broken and possibly to add few more tests for the new header.

Let me know if you need some help.

Regards,
Tomislav Karastojković

**Comment by EarthlingKira** [comment]
I stumbled upon one roadblock: The method set the "From:" header is the following:

`    /**
    Setting the sender to the given address.

    @param mail Mail address to set.
    **/
    void sender(const mail_address& mail);`

So this method is named "sender" but does not set the "Sender:" header and instead sets the "From" header. This is confusing and the proper way would be to change this function to set the sender header and create a new function which sets the From header, but that would be a breaking change. Would you accept such a breaking change in theory?

But I can also imagine 3 options for backwards compatibility:

1) If you only call `sender()` (but do not call the new `from()` setter) it will set both Sender and From.

2) There are 2 new methods with very clear and consistent names and the sender method will call the method with the new name and be marked with [[deprecated]]

3) The sender method gets a second parameter (like a boolean) with a default value to create this backwards compatibility


which one do you prefer?

**Comment by karastojko** [comment]
@EarthlingKira I am fine with breaking the backward compatibility. One of the reasons why the version is still 0.x is that I am still prepared for such cases. Probably there will be few changes in resulting build files, since there is pull request to include Autoconfig.

**Comment by karastojko** [comment]
Fixed with the latest changes under tag `version_0-16-0` of the master branch.

**Comment by EarthlingKira** [comment]
@karastojko Thanks for doing it without my pull request!

**Comment by karastojko** [comment]
No problem, let me know if you encounter any issues.

**Comment by EarthlingKira** [comment]
As a comment: thanks for your work, sender header is working perfectly (tested while sending emails for our software users, they enter their own "From" email address, but we don't have their email credentials and send it with our own email account. When setting the sender header to our own email account gmail for example accepts the emails and no longer spam filters them)

**Comment by karastojko** [comment]
I am glad it works.

Regards,
