### ISSUE TITLE
Ditch boost dependancy

### ISSUE THREAD

**Issue by Oberonc** [karastojko/mailio#4]
Why is boost a dependency ?
All the algorithms are implemented in c++11/c++14/c++17

**Comment by karastojko** [comment]
Hi @Oberonc,

Thanks for the comment. Can you please be more specific which are algorithms you were talking about? Since the core of the library relies on Boost.Asio, that library is necessary at least. There are few string algorithms that are used too. As I can recall, std regex was incomplete in the past, so I have used this one from Boost. Probably I will switch back to std in the future.

Regards,

**Comment by EarthlingKira** [comment]
@Oberonc I'm pretty sure that there is no async network replacement in the C++ standard library to use and reimplementing it would be much more complex and reinventing the wheel.


@karastojko  std regex is now implemented in libstdc++ (and even longer in libc++) but they are inconsistent, see: https://stackoverflow.com/q/46001379 , so it may be a good idea to stick to boost

**Comment by IceflowRE** [comment]
I would like to take up the topic, but boost asio is available as standalone.

Which other parts are relying on boost?
How much work would it be to remove boost as a dependency?

**Comment by karastojko** [comment]
Something like [this](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2054.pdf) has to be accepted in order to get rid of Boost. Also there are string and date manipulations used from Boost.
